# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 6580f42134f02e5eca7e955b44ec307529f22381

{
  "title": "Шкаф IKEA17",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/19/
Content-Type: application/json
Authorization: Token 6580f42134f02e5eca7e955b44ec307529f22381

{
"status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-06-10
Content-Type: application/json
