# Generated by Django 4.0.5 on 2022-06-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_scope_alter_article_options_tag_scope_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'РАЗДЕЛЫ', 'verbose_name_plural': 'РАЗДЕЛЫ'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'ТЕМАТИКА', 'verbose_name_plural': 'ТЕМАТИКИ СТАТЬИ'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='ОСНОВНОЙ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.scope', verbose_name='РАЗДЕЛ'),
        ),
    ]
