# Generated by Django 4.0.5 on 2022-06-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'иЗМЕРЕНИЕ датчика',
                'verbose_name_plural': 'иЗМЕРЕНИЯ датчика',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура при измерении')),
                ('created_at', models.DateTimeField(verbose_name='Дата замера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение замера')),
                ('id_sensor', models.ManyToManyField(related_name='measurements', through='measurement.Chain', to='measurement.sensor', verbose_name='ID датчика')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chain',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='measurement.measurement'),
        ),
        migrations.AddField(
            model_name='chain',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='measurement.sensor'),
        ),
    ]
