# Generated by Django 4.0.5 on 2022-06-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='id_sensor',
        ),
        migrations.AddField(
            model_name='chain',
            name='id_sensor',
            field=models.PositiveIntegerField(default=999, verbose_name='ID датчика'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ManyToManyField(related_name='measurements', through='measurement.Chain', to='measurement.sensor'),
        ),
    ]
